import { randomUUID } from "node:crypto";
import { createRequire } from "node:module";
import path from "node:path";
import { expect, test } from "@playwright/test";
import { appointmentTimeInput } from "../../src/lib/appointment-time";
import type { ApiAppointment, ApiClinicSchedule } from "../../src/lib/server/vetlinx-api";

test.use({ timezoneId: "Asia/Dubai" });
const fixtureDatabase = process.env.B2C_TEST_DATABASE_URL;
test("clinic publishes availability; owner books, reschedules and releases capacity through the real BFF", async ({page, browser}, testInfo) => {
  test.skip(!fixtureDatabase, "Set B2C_TEST_DATABASE_URL to the disposable database used by the running API.");
  test.setTimeout(120_000);
  if (!fixtureDatabase || !new URL(fixtureDatabase).pathname.toLowerCase().includes("test")) throw new Error("Scheduling fixtures require an explicitly named test database.");
  const requireApi = createRequire(path.resolve("apps/api/package.json"));
  const {Client} = requireApi("pg") as {Client: new (config: {connectionString: string}) => {connect(): Promise<void>; end(): Promise<void>; query(sql: string, values: unknown[]): Promise<unknown>}};
  const database = new Client({connectionString: fixtureDatabase});
  await database.connect();
  const baseURL = process.env.BASE_URL ?? "http://localhost:3000";
  const clinicContext = await browser.newContext({baseURL, viewport: testInfo.project.use.viewport, timezoneId: "Asia/Dubai"});
  const clinicPage = await clinicContext.newPage();
  const stamp = `${testInfo.project.name}-${randomUUID()}`;
  const clinicName = `Published Care ${stamp}`;
  const firstTime = appointmentTimeInput(new Date(Date.now() + 3 * 86400000), "Asia/Dubai");
  const secondTime = appointmentTimeInput(new Date(Date.now() + 4 * 86400000), "Asia/Dubai");
  try {
    const registration = await clinicContext.request.post("/api/session/register", {data: {email: `clinic-${stamp}@scheduling.test`, password: "Clinic-Scheduling-Fixture-2026"}});
    expect(registration.ok()).toBeTruthy();
    const created = await clinicContext.request.post("/api/organizations", {data: {legalName: clinicName, type: "CLINIC", countryCode: "AE", city: "Dubai", phone: "+97140000000"}});
    expect(created.ok()).toBeTruthy();
    const {workspace} = await created.json() as {workspace: {organization: {id: string}}};
    const organizationId = workspace.organization.id;
    await database.query("UPDATE organizations.organizations SET status = $1 WHERE id = $2", ["VERIFIED", organizationId]);
    await clinicPage.goto("/employer/appointments");
    await clinicPage.getByRole("button", {name: "Enable appointment requests"}).click();
    await expect(clinicPage.getByRole("heading", {name: "Accepting appointment requests"})).toBeVisible();
    await clinicPage.getByText(/Services and availability ·/).click();
    const resourceForm = clinicPage.getByRole("form", {name: "Add clinic resource"});
    await resourceForm.getByLabel("Resource name").fill("Consultation room 1");
    await resourceForm.getByRole("button", {name: "Add resource", exact: true}).click();
    await expect(clinicPage.getByRole("heading", {name: "Consultation room 1 · Room · Available"})).toBeVisible();
    const serviceForm = clinicPage.getByRole("form", {name: "Add clinic service"});
    await serviceForm.getByLabel("Service name").fill("Wellness examination");
    await serviceForm.getByLabel("Service description").fill("Routine wellness examination for your pet");
    await serviceForm.getByLabel("Duration in minutes").fill("30");
    await serviceForm.getByRole("button", {name: "Add draft service"}).click();
    await expect(clinicPage.getByRole("heading", {name: "Wellness examination · 30 minutes · Draft"})).toBeVisible();
    const slotForm = clinicPage.getByRole("form", {name: "Publish appointment time"});
    await slotForm.getByLabel("Available date and time").fill(firstTime);
    await slotForm.getByRole("checkbox", {name: "Consultation room 1"}).check();
    await slotForm.getByRole("button", {name: "Publish time", exact: true}).click();
    await expect(clinicPage.getByRole("button", {name: "Close this time"})).toHaveCount(1);
    await slotForm.getByLabel("Available date and time").fill(secondTime);
    await slotForm.getByRole("checkbox", {name: "Consultation room 1"}).check();
    await slotForm.getByRole("button", {name: "Publish time", exact: true}).click();
    await expect(clinicPage.getByRole("button", {name: "Close this time"})).toHaveCount(2);
    await clinicPage.getByRole("button", {name: "Publish service", exact: true}).click();
    await expect(clinicPage.getByRole("heading", {name: "Wellness examination · 30 minutes · Published"})).toBeVisible();
    await clinicPage.getByRole("button", {name: "Use published times"}).click();
    await expect(clinicPage.getByRole("heading", {name: "Owners choose published times"})).toBeVisible();
    await clinicPage.evaluate(() => { window.scrollTo(0, 0); if (document.activeElement instanceof HTMLElement) document.activeElement.blur(); });
    await clinicPage.screenshot({path: `playwright-report/scheduling-qa/${testInfo.project.name}-real-clinic-published.png`, fullPage: true});

    await page.goto("/register?intent=owner");
    await page.getByLabel("Email", {exact: true}).fill(`owner-${stamp}@scheduling.test`);
    await page.getByLabel("Password", {exact: true}).fill("Owner-Scheduling-Fixture-2026");
    await page.getByRole("button", {name: "Create account", exact: true}).click();
    await page.getByLabel("Your name").fill("Samira Hassan");
    await page.getByLabel("Contact phone").fill("+971501234567");
    await page.getByRole("button", {name: "Create pet-owner profile"}).click();
    await page.getByRole("button", {name: "Add pet", exact: true}).click();
    await page.getByLabel("Pet name").fill("Luna");
    await page.getByRole("combobox", {name: "Species", exact: true}).selectOption("CAT");
    await page.getByRole("button", {name: "Save pet"}).click();
    await expect(page.getByRole("heading", {name: "Luna", exact: true})).toBeVisible();
    await page.goto("/clinics");
    await page.getByLabel("Clinic name").fill(clinicName);
    await page.getByRole("button", {name: "Search clinics"}).click();
    await page.getByRole("article").filter({has: page.getByRole("heading", {name: clinicName, exact: true})}).getByRole("button", {name: "Request appointment"}).click();
    const available = await (await page.request.get(`/api/clinics/${organizationId}/availability`)).json() as {schedule: ApiClinicSchedule};
    expect(available.schedule.slots).toHaveLength(2);
    expect(available.schedule.resources).toBeUndefined();
    expect(available.schedule.slots.every(slot => slot.resources === undefined)).toBeTruthy();
    const [original, alternative] = available.schedule.slots;
    await page.getByRole("combobox", {name: "Service", exact: true}).selectOption(available.schedule.services[0].id);
    await page.getByRole("combobox", {name: "Available time", exact: true}).selectOption(original.id);
    await page.getByRole("button", {name: "Hold this time"}).click();
    await expect(page.getByRole("region", {name: "Your held time"})).toBeVisible();
    await page.getByLabel("Reason for visit").fill("Annual wellness examination");
    await page.getByLabel(/I agree to share my name/).check();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBeTruthy();
    await page.evaluate(() => { window.scrollTo(0, 0); if (document.activeElement instanceof HTMLElement) document.activeElement.blur(); });
  await page.screenshot({path: `playwright-report/scheduling-qa/${testInfo.project.name}-real-owner-held.png`, fullPage: true});
    await page.getByRole("button", {name: "Send appointment request"}).click();
    await expect(page.getByRole("main").getByRole("status")).toContainText("Your request has been sent");
    await page.goto("/owner");
    await expect(page.getByText(/A place is reserved at the selected time/)).toBeVisible();
    const getAppointment = async () => ((await (await page.request.get("/api/appointments")).json()) as {appointments: ApiAppointment[]}).appointments[0];
    expect(await getAppointment()).toMatchObject({slotId: original.id, serviceName: "Wellness examination", durationMinutes: 30, status: "REQUESTED"});

    await clinicPage.getByRole("button", {name: "Refresh", exact: true}).click();
    await clinicPage.getByRole("button", {name: "Confirm time", exact: true}).click();
    await expect(clinicPage.getByText("confirmed", {exact: true})).toBeVisible();
    await page.getByRole("button", {name: "Refresh", exact: true}).click();
    await page.getByRole("button", {name: "Request a different time", exact: true}).click();
    await page.getByRole("combobox", {name: "Published alternative time", exact: true}).selectOption(alternative.id);
    await page.getByLabel(/Response deadline/).fill(appointmentTimeInput(new Date(Date.now() + 86400000), "Asia/Dubai"));
    await page.getByLabel("Reason for rescheduling").fill("Please move this visit to fit my work schedule");
    await page.evaluate(() => { window.scrollTo(0, 0); if (document.activeElement instanceof HTMLElement) document.activeElement.blur(); });
  await page.screenshot({path: `playwright-report/scheduling-qa/${testInfo.project.name}-real-owner-reschedule.png`, fullPage: true});
    await page.getByRole("button", {name: "Send reschedule request"}).click();
    await expect(page.getByRole("heading", {name: "Owner requested a different time"})).toBeVisible();
    expect(await getAppointment()).toMatchObject({slotId: original.id, proposedSlotId: alternative.id, startsAt: original.startsAt});
    await clinicPage.getByRole("button", {name: "Refresh", exact: true}).click();
    await clinicPage.getByRole("button", {name: "Accept reschedule request"}).click();
    await clinicPage.getByRole("button", {name: "Confirm time change"}).click();
    await expect(clinicPage.getByRole("heading", {name: "Owner requested a different time"})).toHaveCount(0);
    await page.getByRole("button", {name: "Refresh", exact: true}).click();
    expect(await getAppointment()).toMatchObject({slotId: alternative.id, proposedSlotId: null, startsAt: alternative.startsAt, status: "CONFIRMED"});
    const moved = await (await page.request.get(`/api/clinics/${organizationId}/availability`)).json() as {schedule: ApiClinicSchedule};
    expect(moved.schedule.slots.find(slot => slot.id === original.id)?.remaining).toBe(1);
    expect(moved.schedule.slots.find(slot => slot.id === alternative.id)?.remaining).toBe(0);
    await page.getByRole("button", {name: "Cancel request for Luna"}).click();
    await page.getByRole("button", {name: "Confirm cancellation", exact: true}).click();
    await expect(page.getByRole("button", {name: "History (1)"})).toBeVisible();
    expect((await getAppointment()).status).toBe("CANCELLED");
    const released = await (await page.request.get(`/api/clinics/${organizationId}/availability`)).json() as {schedule: ApiClinicSchedule};
    expect(released.schedule.slots.every(slot => slot.remaining === 1)).toBeTruthy();
    await clinicPage.getByRole("button", {name: "Refresh schedule"}).click();
    for (let index = 0; index < 2; index++) {
      await clinicPage.getByRole("button", {name: "Close this time"}).first().click();
      await expect(clinicPage.getByRole("button", {name: "Close this time"})).toHaveCount(1 - index);
      await clinicPage.getByRole("button", {name: "Release unused resources"}).first().click();
      await expect(clinicPage.getByText(/^Resources released:/)).toHaveCount(index + 1);
    }
    await clinicPage.getByRole("button", {name: "Retire Consultation room 1"}).click();
    await clinicPage.getByRole("button", {name: "Confirm retirement"}).click();
    await expect(clinicPage.getByRole("heading", {name: "Consultation room 1 · Room · Retired"})).toBeVisible();
    await clinicPage.evaluate(() => {if (document.activeElement instanceof HTMLElement) document.activeElement.blur(); window.scrollTo(0, 0);});
    await clinicPage.screenshot({path: `playwright-report/resource-qa/${testInfo.project.name}-real-retired-resource.png`, fullPage: true});
  } finally {
    await clinicContext.close();
    await database.end();
  }
});
