import { expect, test } from "@playwright/test";
import { TOTP } from "../../apps/api/node_modules/otpauth";

test("a real account enrolls in MFA and signs back in through a one-use recovery code", async ({ page }, testInfo) => {
  const email = `mfa.journey.${testInfo.project.name}.${Date.now()}@vetlinx.test`;
  const password = "Real-Mfa-Account-Journey-2026";
  await page.goto("/register");
  await page.getByLabel("Email", { exact: true }).fill(email);
  await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Create account", exact: true }).click();
  await expect(page).toHaveURL(/\/get-started$/);
  await page.goto("/settings/security/mfa");
  await page.getByLabel("Current password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Start setup", exact: true }).click();
  await expect(page.getByAltText("Private authenticator setup QR code")).toBeVisible();
  const secret = (await page.getByRole("main").locator("pre").innerText()).trim();
  const code = new TOTP({ secret, algorithm: "SHA1", digits: 6, period: 30 }).generate();
  await page.getByLabel("Six-digit authenticator code").fill(code);
  await page.getByRole("button", { name: "Enable two-step verification", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Save your recovery codes now" })).toBeVisible();
  const recoveryCode = (await page.getByRole("main").locator("pre").innerText()).split("\n")[0].trim();
  await page.getByRole("button", { name: "I have saved my codes", exact: true }).click();
  const logout = await page.request.post("/api/session/logout", { headers: { origin: process.env.BASE_URL ?? "http://localhost:3000" } });
  expect(logout.status()).toBe(204);
  await page.goto("/login?returnTo=%2Fsettings%2Fsecurity%2Fmfa");
  await page.getByLabel("Email", { exact: true }).fill(email);
  await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Confirm your sign-in" })).toBeVisible();
  expect((await page.context().cookies()).some((cookie) => /access|refresh/.test(cookie.name) && cookie.value)).toBe(false);
  await page.getByLabel("Authenticator or recovery code", { exact: true }).fill(recoveryCode);
  await page.getByRole("button", { name: "Verify and sign in", exact: true }).click();
  await expect(page).toHaveURL(/\/settings\/security\/mfa$/);
  await expect(page.getByText("Two-step verification enabled", { exact: true })).toBeVisible();
  await expect(page.getByText("9 unused recovery codes remain.", { exact: true })).toBeVisible();
  await page.getByLabel("Authenticator or recovery code", { exact: true }).fill(recoveryCode);
  await page.getByRole("button", { name: "Confirm identity for 15 minutes", exact: true }).click();
  await expect(page.getByRole("main").getByRole("alert")).toContainText("invalid, expired, or already used");
  await page.goto("/settings/notifications");
  const reminders = page.getByRole("checkbox", { name: /^Appointment reminders/ });
  await reminders.uncheck();
  await page.getByRole("button", { name: "Save preferences", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("preferences have been saved");
  await page.reload();
  await expect(reminders).not.toBeChecked();
});
