import { expect, test } from "@playwright/test";

test("one account creates an owner profile, manages pets, and adds a professional workspace", async ({ page }, testInfo) => {
  test.setTimeout(75_000);
  await page.goto("/register");
  await page.getByLabel("Email", { exact: true }).fill(`owner-${testInfo.project.name}-${Date.now()}@example.test`);
  await page.getByLabel("Password", { exact: true }).fill("VetLinX-Owner-Account-2026");
  await page.getByRole("button", { name: "Create account", exact: true }).click();
  await expect(page).toHaveURL(/\/get-started$/);
  await page.getByRole("link", { name: "Continue as a pet owner" }).click();
  await page.getByLabel("Your name").fill("Maya Rahman");
  await page.getByLabel("Contact phone").fill("+971 50 123 4567");
  await page.getByRole("button", { name: "Create pet-owner profile" }).click();
  await expect(page).toHaveURL(/\/owner$/);
  await expect(page.getByRole("heading", { name: "Add your first pet" })).toBeVisible();
  const accessCookie = (await page.context().cookies()).find((cookie) => cookie.name === "vetlinx_access");
  if (!accessCookie) throw new Error("Missing access cookie");
  await page.context().addCookies([{ ...accessCookie, value: "expired-access-token" }]);
  const refreshed = await Promise.all(["/api/session/me", "/api/pets", "/api/appointments"].map((url) => page.request.get(url)));
  expect(refreshed.every((response) => response.ok())).toBeTruthy();
  await page.getByRole("button", { name: "Add pet", exact: true }).click();
  await page.getByLabel("Pet name").fill("Luna");
  await page.getByRole("combobox", { name: "Species", exact: true }).selectOption("CAT");
  await page.getByLabel("Breed (optional)").fill("Domestic shorthair");
  await page.getByRole("button", { name: "Save pet" }).click();
  await expect(page.getByRole("heading", { name: "Luna", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Edit Luna", exact: true }).click();
  await page.getByLabel("Pet name").fill("Luna Rose");
  await page.getByRole("button", { name: "Save pet" }).click();
  await expect(page.getByRole("heading", { name: "Luna Rose", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Archive Luna Rose" }).click();
  await page.getByRole("button", { name: "Confirm archive" }).click();
  await expect(page.getByRole("heading", { name: "Add your first pet" })).toBeVisible();
  if (testInfo.project.name === "mobile") await page.getByRole("button", { name: "Open navigation" }).click();
  await page.getByRole("button", { name: "Switch workspace: Pet owner", exact: true }).first().click();
  await expect(page.getByRole("menuitem", { name: "Pet owner, Maya Rahman" })).toBeVisible();
  await page.getByRole("menuitem", { name: "Professional, Set up" }).click();
  await page.getByLabel("Professional name").fill("Dr. Maya Rahman");
  await page.getByRole("button", { name: "Create professional profile" }).click();
  await expect(page).toHaveURL(/\/credentials$/);
  const me = await page.request.get("/api/session/me");
  expect(me.ok()).toBeTruthy();
  expect(await me.json()).toMatchObject({ profile: { displayName: "Dr. Maya Rahman" }, owner: { displayName: "Maya Rahman" } });
  // Switching back and forth must use the explicit destination, even when / was prefetched.
  if (testInfo.project.name === "mobile") await page.getByRole("button", { name: "Open navigation" }).click();
  await page.getByRole("button", { name: "Switch workspace: Professional", exact: true }).first().click();
  await page.getByRole("menuitem", { name: "Pet owner, Maya Rahman" }).click();
  await expect(page).toHaveURL(/\/owner$/);
  await page.request.get("/");
  if (testInfo.project.name === "mobile") await page.getByRole("button", { name: "Open navigation" }).click();
  await page.getByRole("button", { name: "Switch workspace: Pet owner", exact: true }).first().click();
  await page.getByRole("menuitem", { name: "Professional, Dr. Maya Rahman" }).click();
  await expect(page).toHaveURL(/\/professional$/);
  await expect(page.getByRole("heading", { name: "Hello, Dr. Maya Rahman" })).toBeVisible();
  await page.reload();
  await expect(page).toHaveURL(/\/professional$/);
  await expect(page.getByRole("heading", { name: "Hello, Dr. Maya Rahman" })).toBeVisible();
  if (testInfo.project.name === "mobile") await page.getByRole("button", { name: "Open navigation" }).click();
  await page.getByRole("button", { name: "Switch workspace: Professional", exact: true }).first().click();
  await page.getByRole("menuitem", { name: "Pet owner, Maya Rahman" }).click();
  await expect(page).toHaveURL(/\/owner$/);
  // Owner preference must never override a direct professional link.
  await page.goto("/professional");
  await expect(page.getByRole("heading", { name: "Hello, Dr. Maya Rahman" })).toBeVisible();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: testInfo.outputPath("professional-workspace.png"), fullPage: true });
  await page.goto("/owner");
  await expect(page.getByRole("heading", { name: "Hello, Maya Rahman" })).toBeVisible();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: testInfo.outputPath("owner-workspace.png"), fullPage: true });
});
