"use client";
import { BriefcaseBusiness, FileCheck2, LoaderCircle, Mail, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { BrandMark } from "@/components/brand/BrandMark";
import type { ApiPortfolio } from "@/lib/server/vetlinx-api";
import styles from "./Portfolio.module.css";

export function PublicPortfolio({slug}:{slug:string}){const [portfolio,setPortfolio]=useState<ApiPortfolio|null>(null);const [missing,setMissing]=useState(false);useEffect(()=>{fetch(`/api/public/portfolio/${encodeURIComponent(slug)}`,{cache:"no-store"}).then(async(r)=>{const b=await r.json().catch(()=>({})) as {portfolio?:ApiPortfolio};if(!r.ok||!b.portfolio)throw new Error();setPortfolio(b.portfolio)}).catch(()=>setMissing(true))},[slug]);if(missing)return <main className={styles.publicEmpty}><BrandMark/><h1>Portfolio not available</h1><p>This record is private, unpublished, or does not exist.</p><Link href="/">Visit VetLinX</Link></main>;if(!portfolio)return <main className={styles.loading}><LoaderCircle/>Loading verified portfolio…</main>;return <div className={styles.publicPage}><header><BrandMark/><span><ShieldCheck/>Verified VetLinX record</span></header><main><section className={styles.publicHero}><span className={styles.avatar}>{portfolio.displayName.split(/\s+/).slice(0,2).map(p=>p[0]).join("")}</span><div><h1>{portfolio.displayName}</h1><h2>{portfolio.headline||"Veterinary professional"}</h2><p>{portfolio.countryCode}</p></div>{portfolio.email?<a href={`mailto:${portfolio.email}`}><Mail/>Contact</a>:null}</section>{portfolio.summary?<section><h2>Professional summary</h2><p>{portfolio.summary}</p></section>:null}<div className={styles.publicGrid}><section><h2><FileCheck2/>Verified credentials</h2>{portfolio.credentials.map(c=><article key={c.id}><strong>{c.title}</strong><p>{c.issuingOrganization} · {c.countryCode}</p><span>Verified</span></article>)}</section><section><h2><BriefcaseBusiness/>Confirmed employment</h2>{portfolio.employments.map(e=><article key={e.id}><strong>{e.title}</strong><p>{e.organization.publicName??e.organization.legalName}</p><span>{new Date(e.startDate).getFullYear()}–{e.endDate?new Date(e.endDate).getFullYear():"Present"}</span></article>)}</section></div></main><footer>Claims marked verified are backed by governed VetLinX evidence or organization confirmation.</footer></div>}
